/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exp;

import com.fazecast.jSerialComm.SerialPort;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * Updates container information
     */
    private void rewriteContainers() {
        try {
            FileWriter containerRestore = new FileWriter("container.txt");
            containerRestore.write(xc + "\r\n");
            containerRestore.write(yc + "\r\n");
            containerRestore.write(zc + "\r\n");
            containerRestore.write(mony_ventas + "\r\n");
            containerRestore.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Method that calculates the change that the machine will give you
     */
    private void giveChange(int value) {
        String s1 = "C" + (c - value);
        byte[] b = s1.getBytes(StandardCharsets.US_ASCII);
        s[1].writeBytes(b, b.length);

        c = 0;
        Mony.setText(c + "");
    }

    /**
     * Method that activates the soda you bought
     */
    private void giveProd(int ch, int val) {
        String s1 = "R" + ch + "" + (c - val);
        byte[] b = s1.getBytes(StandardCharsets.US_ASCII);
        s[1].writeBytes(b, b.length);

        c = 0;
        Mony.setText(c + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        can = new javax.swing.JButton();
        r1 = new javax.swing.JButton();
        r2 = new javax.swing.JButton();
        r3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Mony = new javax.swing.JLabel();
        xco = new javax.swing.JLabel();
        yco = new javax.swing.JLabel();
        zco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        can.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        can.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exp/c.jpg"))); // NOI18N
        can.setText("Cancelar Compra");
        can.setEnabled(false);
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });

        r1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exp/z.jpg"))); // NOI18N
        r1.setText("Comprar Refresco X");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exp/y.jpg"))); // NOI18N
        r2.setText("Comprar Refresco Y");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exp/z.jpg"))); // NOI18N
        r3.setText("Comprar Refresco Z");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        jButton5.setText("Start");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dinero introducido:");

        Mony.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Mony.setText("0");

        xco.setText("0");

        yco.setText("0");

        zco.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xco, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(35, 35, 35)
                        .addComponent(Mony, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Mony)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(xco)
                            .addComponent(r2)
                            .addComponent(yco)))
                    .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r3)
                    .addComponent(zco)
                    .addComponent(can))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Method that starts the soda machine
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        for (int i = 0; i < s.length; i++) {
            System.out.println(s[i].getSystemPortName());

        }
        s[1].openPort();
        s[1].setBaudRate(9600);
        //background thread
        Thread back;
        back = new Thread() {
            public void run() {
                try {
                    //infinite loop
                    while (true) {
                        //wait for data
                        while (s[1].bytesAvailable() == 0) {
                            Thread.sleep(20);
                        }

                        byte[] readBuffer = new byte[s[1].bytesAvailable()];
                        s[1].readBytes(readBuffer, readBuffer.length);
                        //user pressed Tiva C sensor for $1
                        if (readBuffer[0] == '1') {
                            if (c + 1 > 9) {
                                String s1 = "C1";
                                byte[] b = s1.getBytes(StandardCharsets.US_ASCII);
                                s[1].writeBytes(b, b.length);
                            } else {

                                c++;
                                Mony.setText(c + "");
                            }

                        }
                        //user pressed Tiva C sensor for $2
                        else if (readBuffer[0] == '2') {
                            if (c + 2 > 9) {
                                String s1 = "C2";
                                byte[] b = s1.getBytes(StandardCharsets.US_ASCII);
                                s[1].writeBytes(b, b.length);

                            } else {
                                c = c + 2;
                                Mony.setText(c + "");
                            }
                        }
                        //print received data
                        //System.out.println(new String(readBuffer));
                    }
                } catch (InterruptedException e) {
                    //something went wrong
                    e.printStackTrace();
                    s[1].closePort();
                }
            }

        };
        //start  money process
        back.start();
        //thread used to control available sodas
        Thread moni = new Thread() {
            public void run() {
                try {
                    can.setEnabled(true);
                    while (true) {
                        if (c > 5 && xc > 0) {
                            r1.setEnabled(true);
                        } else {
                            r1.setEnabled(false);
                        }
                        if (c > 6 && yc > 0) {
                            r2.setEnabled(true);
                        } else {
                            r2.setEnabled(false);
                        }
                        if (c > 7 && zc > 0) {
                            r3.setEnabled(true);
                        } else {

                            r3.setEnabled(false);

                        }
                        xco.setText(xc + "");
                        yco.setText(yc + "");
                        zco.setText(zc + "");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    s[1].closePort();
                }
            }

        };
        //start  money validation
        moni.start();
        //read las values of inventory in soda machine
        try {
            Scanner con = new Scanner(new File("C:\\Users\\da supa pc\\Documents\\NetBeansProjects\\Exp\\container.txt"));
            xc = Integer.parseInt(con.nextLine());
            yc = Integer.parseInt(con.nextLine());
            zc = Integer.parseInt(con.nextLine());
            mony_ventas = Integer.parseInt(con.nextLine());
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        jButton5.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed
  /** user cancels process
   */
    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        giveChange(0);


    }//GEN-LAST:event_canActionPerformed
/** user buys soda X
 */
    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        try {
            FileWriter rep1 = new FileWriter("reporte de refresco x.txt", true);
            rep1.write(DateFormat.getDateTimeInstance().format(now) + "\r\n");
            rep1.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        giveProd(0, 6);
        xc--;
        mony_ventas = mony_ventas + 6;
        rewriteContainers();


    }//GEN-LAST:event_r1ActionPerformed
/**user buys soda Y
 */
    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        try {
            FileWriter rep1 = new FileWriter("reporte de refresco y.txt", true);
            rep1.append(DateFormat.getDateTimeInstance().format(now) + "\r\n");
            rep1.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        giveProd(1, 7);
        yc--;
        mony_ventas = mony_ventas + 7;
        rewriteContainers();
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed
/**user buys soda Z
 */
    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        try {
            FileWriter rep1 = new FileWriter("reporte de refresco z.txt", true);
            rep1.append(DateFormat.getDateTimeInstance().format(now) + "\r\n");
            rep1.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        giveProd(2, 8);
        zc--;
        mony_ventas = mony_ventas + 8;
        rewriteContainers();
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mony;
    private javax.swing.JButton can;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton r1;
    private javax.swing.JButton r2;
    private javax.swing.JButton r3;
    private javax.swing.JLabel xco;
    private javax.swing.JLabel yco;
    private javax.swing.JLabel zco;
    // End of variables declaration//GEN-END:variables
    private int c = 0;
    private SerialPort s[] = SerialPort.getCommPorts();
    private Date now = new Date();
    private int xc = 20;
    private int yc = 20;
    private int zc = 20;
    private int mony_ventas = 0;
}
